KeyError fix 2
Solves
KeyError: "Unable to open object (object 'Spectrum RMSE Train (Ha)' doesn't exist)"
-> forgot to upload the new hdf5 file which has that key