KeyError fix 1
Solves
KeyError: "Unable to open object (object '['E0', 't']' doesn't exist)"
-> Now saves the parameters as unmashed parameters[0] inside 'onebody' and parameters[1] inside 'twobody'